version: "3"

services:
  db:
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:14.10-alpine3.19
    container_name: fmd-db
    networks:
      - fmd-backend
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: fmd-adminer
    networks:
      - fmd-backend
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - 8080:8080

networks:
  fmd-backend:

volumes:
  db-data:
